vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        personnes:
            uri_prefix: /images/personnes
            upload_destination: '%kernel.project_dir%/public/images/personnes'
